// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RisingStates",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "RisingStates",
            targets: ["AppModule"],
            bundleIdentifier: "com.luke.RisingStates",
            teamIdentifier: "2MD4NXFV5G",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .strategyGames
        )
    ],
    dependencies: [
        .package(url: "https://github.com/crashoverride777/swifty-sk-scroll-view", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftySKScrollView", package: "swifty-sk-scroll-view")
            ],
            path: ".",
            resources: [
                .process("Audio")
            ]
        )
    ]
)
